apiVersion: v1
kind: ConfigMap
metadata:
  name: course-service-config
  namespace: university
data:
  PORT: "3002"
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://postgres:postgres@course-db:5432/course_db"
