apiVersion: v1
kind: ConfigMap
metadata:
  name: enrollment-service-config
  namespace: university
data:
  PORT: "3004"
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://postgres:postgres@enrollment-db:5432/enrollment_db"
