apiVersion: v1
kind: ConfigMap
metadata:
  name: student-service-config
  namespace: university
data:
  PORT: "3001"
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://postgres:postgres@student-db:5432/student_db"
